//// Author: Ryu Sawada
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TMTT1                                                                      //
//                                                                            //
// 
// 
// This header has been generated by the ArgusBuilder.
//                                                                            //
//                                                                            //
/////////////////////////////////////----///////////////////////////////////////

#include "include/tabs/TMTT1.h"

ClassImp(TMTT1)
   
void TMTT1::Init()
{
   // Create a vertical frame containing buttons and canvas 
   fVert = new TGVerticalFrame(fParent, (UInt_t)(700*gMonitor->GetWindowScale()), (UInt_t)(700*gMonitor->GetWindowScale()));
   
   // Create an embedded canvas and add to the main frame, centered in x and y 
   fCanvas = new TRootEmbeddedCanvas("Tab1", fVert, (UInt_t)(600*gMonitor->GetWindowScale()), (UInt_t)(600*gMonitor->GetWindowScale()));
   
   // Create a text
   fText = new TLatex(0.5,0.5,"Menu Tab 1.");
   fText->SetTextAlign(22);
   
   fVert->AddFrame(fCanvas,
                   new TGLayoutHints(kLHintsExpandX | kLHintsExpandY, 4, 4, 4, 4));
   AddFrame(fVert, new TGLayoutHints( kLHintsExpandX | kLHintsExpandY, 10, 10, 4, 4));
   
   fCanvas->GetCanvas()->cd();
   fText->Draw();
   fCanvas->GetCanvas()->Modified();
   fCanvas->GetCanvas()->Update(); 
}

void TMTT1::MenuClicked(Long_t param)
{
   switch (param){
      case 1:
	 fText->SetTextColor(1);
	 break;
      case 2:
	 fText->SetTextColor(2);
	 break;
      case 3:
	 fText->SetTextColor(3);
	 break;
      case 4:
	 fText->SetTextColor(4);
	 break;
      case 11:
	 fText->SetTextSize(0.03);
	 break;
      case 12:
	 fText->SetTextSize(0.08);
	 break;
      case 13:
	 fText->SetTextSize(0.15);
	 break;
   }
   fCanvas->GetCanvas()->cd();
   fText->Draw();
   fCanvas->GetCanvas()->Modified();
   fCanvas->GetCanvas()->Update(); 
}

