// Author: Ryu Sawada <http://www.icepp.s.u-tokyo.ac.jp/%7Esawada>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TBTTab1_2                                                                  //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TBTTab1_2GeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TBWindow.h"
#include "generated/TBAnalyzer.h"
#include "tabs/TBTTab1_2.h"

// uncomment if you want to include headers of all folders
//#include "TBAllFolders.h"


ClassImp(TBTTab1_2)

void TBTTab1_2::Init()
{
}

void TBTTab1_2::EndInit()
{
}

void TBTTab1_2::EventHandler()
{
}

void TBTTab1_2::MenuClicked(TGPopupMenu * /* menu */,Long_t /* param */)
{
}

void TBTTab1_2::TabSelected()
{
}
void TBTTab1_2::TabUnSelected()
{
}

