// Author: Ryu Sawada

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TBTTab2_1                                                                  //
//                                                                            //
// Description:                                                               //
//                                                                            //
//                                                                            //
// Usage:                                                                     //
//                                                                            //
//                                                                            //
// Status:                                                                    //
//                                                                            //
//                                                                            //
// To Do:                                                                     //
//                                                                            //
//                                                                            //
// Known Problems:                                                            //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TBWindow.h"
#include "generated/TBAnalyzer.h"
#include "tabs/TBTTab2_1.h"

// uncomment if you want to include headers of all folders
//#include "TBAllFolders.h"


ClassImp(TBTTab2_1)

void TBTTab2_1::Init()
{
}

void TBTTab2_1::EndInit()
{
}

void TBTTab2_1::EventHandler()
{
}

void TBTTab2_1::MenuClicked(TGPopupMenu * /* menu */,Long_t /* param */)
{
}

void TBTTab2_1::TabSelected()
{
}
void TBTTab2_1::TabUnSelected()
{
}

