// Author: Ryu Sawada

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TBTTab1                                                                    //
//                                                                            //
// Begin_Html                                                                 //
//                                                                            //
// Description:                                                               //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Usage:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Status:                                                                    //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// To Do:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Known Problems:                                                            //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// End_Html                                                                   //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TBWindow.h"
#include "generated/TBAnalyzer.h"
#include "tabs/TBTTab1.h"

// uncomment if you want to include headers of all folders
//#include "TBAllFolders.h"


ClassImp(TBTTab1)

void TBTTab1::Init()
{
}

void TBTTab1::EndInit()
{
}

void TBTTab1::EventHandler()
{
}

void TBTTab1::MenuClicked(TGPopupMenu * /* menu */,Long_t /* param */)
{
}

void TBTTab1::TabSelected()
{
}
void TBTTab1::TabUnSelected()
{
}

