#ifndef TCUTGTGeneratedHisto_H
#define TCUTGTGeneratedHisto_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TCUTGTGeneratedHisto                                                       //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TCUTGTGeneratedHisto_Base.h"

class TCUTGWindow;


class TCUTGTGeneratedHisto : public TCUTGTGeneratedHisto_Base
{
protected:

private:
   TCUTGTGeneratedHisto(const TCUTGTGeneratedHisto &c); // not implemented
   TCUTGTGeneratedHisto &operator=(const TCUTGTGeneratedHisto &c); // not implemented

public:
   TCUTGTGeneratedHisto(TCUTGWindow* window = 0):TCUTGTGeneratedHisto_Base(window)
   {
   }

   virtual ~TCUTGTGeneratedHisto()
   {
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(TCUTGTGeneratedHisto,1)
};

#endif   // TCUTGTGeneratedHisto_H
