#ifndef XYZTMyHisto_H
#define XYZTMyHisto_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// XYZTMyHisto                                                                //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include <RConfig.h>
#if defined( R__VISUAL_CPLUSPLUS )
#pragma warning( push )
#pragma warning( disable : 4800 )
#endif // R__VISUAL_CPLUSPLUS
#include <TRootEmbeddedCanvas.h>
#include <TCanvas.h>
#if defined( R__VISUAL_CPLUSPLUS )
#pragma warning( pop )
#endif // R__VISUAL_CPLUSPLUS

#include "include/generated/XYZTMyHisto_Base.h"

class XYZTMyHisto : public XYZTMyHisto_Base
{
protected:
   TRootEmbeddedCanvas *fCanvas;

public:
   XYZTMyHisto():XYZTMyHisto_Base()
   {
   }

   ~XYZTMyHisto()
   {
   }

   void Init();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(XYZTMyHisto,1)
};

#endif   // XYZTMyHisto_H
