////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// SBSTPrintADCValues                                                         //
//                                                                            //
//                                                                            //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     PMTData                                                                //
//                                                                            //
//                                                                            //
// Followings are include files of folders. ROMEBuilder will update it with   //
// reading this source code when you execute it next time.                    //
#include "include/generated/SBSPMTData.h"
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include <include/generated/SBSTPrintADCValues.h>
#include <Riostream.h>

ClassImp(SBSTPrintADCValues)

void SBSTPrintADCValues::Init()
{
}

void SBSTPrintADCValues::BeginOfRun()
{
}

void SBSTPrintADCValues::Event()
{
   for (int i=0;i<10;i++)
      gAnalyzer->GetPMTDataAt(i)->SetADC(i);

   if (gAnalyzer->GetGSP()->GetOutputOnOff()) {
      for (int i=0;i<10;i++)
         cout << gAnalyzer->GetPMTDataAt(i)->GetADC() << endl;
      cout << endl;
   }
}

void SBSTPrintADCValues::EndOfRun()
{
}

void SBSTPrintADCValues::Terminate()
{
}

