#ifndef NFTHistos_H
#define NFTHistos_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// NFTHistos                                                                  //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/NFTHistos_Base.h"

class NFTHistos : public NFTHistos_Base
{
protected:
   TH1F *histo2;
   TRootEmbeddedCanvas *fCanvas;

public:
   NFTHistos():NFTHistos_Base()
   {
   }

   ~NFTHistos()
   {
   }

   void Init();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(NFTHistos,1)
};

#endif   // NFTHistos_H
