// Author: Ryu Sawada

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// HGTMakeHistogram                                                           //
//                                                                            //
// Description:                                                               //
// Create and fill histograms at the begin of run                             //
//                                                                            //
// Usage:                                                                     //
//                                                                            //
//                                                                            //
// Status:                                                                    //
//                                                                            //
//                                                                            //
// To Do:                                                                     //
//                                                                            //
//                                                                            //
// Known Problems:                                                            //
//                                                                            //
//                                                                            //
// The event methods have been written by Ryu Sawada.                         //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
//                                                                            //
// This task contains the following histgrams :                               //
//    hAdc                                                                    //
//                                                                            //
// The histograms are created and saved automaticaly by the task.             //
//                                                                            //
// The following method can be used to get a handle of the histogram :        //
//                                                                            //
// Get<Histogram Name>()                                                      //
//                                                                            //
// For histogram arrays use :                                                 //
//                                                                            //
// Get<Histogram Name>At(Int_t index)                                         //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
#include "generated/HGAnalyzer.h"

#include <include/tasks/HGTMakeHistogram.h>
#include <Riostream.h>
#include <TRandom.h>

ClassImp(HGTMakeHistogram)

TRandom *rndm;

void HGTMakeHistogram::Init()
{
   rndm = new TRandom();
}

void HGTMakeHistogram::BeginOfRun()
{
}

void HGTMakeHistogram::Event()
{
   FillhAdc(rndm->Gaus(2000, 200));
}

void HGTMakeHistogram::EndOfRun()
{
}

void HGTMakeHistogram::Terminate()
{
}
