////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWRTPrintValue                                                             //
//                                                                            //
//                                                                            //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     Data                                                                   //
//                                                                            //
//                                                                            //
// Followings are include files of folders. ROMEBuilder will update it with   //
// reading this source code when it is executed next time.                    //
#include "include/generated/TWRData.h"
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/TWRTPrintValue.h"
#include "Riostream.h"

ClassImp(TWRTPrintValue)

void TWRTPrintValue::Init()
{
}

void TWRTPrintValue::BeginOfRun()
{
}

void TWRTPrintValue::Event()
{
   cout << gAnalyzer->GetData()->GetValue() << endl;
}

void TWRTPrintValue::EndOfRun()
{
}

void TWRTPrintValue::Terminate()
{
}

