// Author: Ryu Sawada

#ifndef PMTThread_H
#define PMTThread_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// PMTThread                                                                  //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/PMTThread_Base.h"
#include <TGButton.h>
#include <TGLayout.h>

class PMTThread : public PMTThread_Base
{
protected:
   TGHorizontalFrame* fHorz;
   TGTextButton*      fButton;

public:
   PMTThread():PMTThread_Base()
   {
      fHorz       = 0;
      fButton     = 0;
   }

   virtual ~PMTThread()
   {
      delete fHorz;
      delete fButton;
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();
   Bool_t ProcessMessageThread(Long_t msg, Long_t param1, Long_t param2);
   void withMakingThread();

   ClassDef(PMTThread,1)
};

#endif   // PMTThread_H
