// Author: Ryu Sawada <http://www.icepp.s.u-tokyo.ac.jp/%7Esawada>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TBTTab1_1                                                                  //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TBTTab1_1GeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TBWindow.h"
#include "generated/TBAnalyzer.h"
#include "tabs/TBTTab1_1.h"

// uncomment if you want to include headers of all folders
//#include "TBAllFolders.h"


ClassImp(TBTTab1_1)

void TBTTab1_1::Init()
{
}

void TBTTab1_1::EndInit()
{
}

void TBTTab1_1::EventHandler()
{
}

void TBTTab1_1::MenuClicked(TGPopupMenu * /* lmenu */,Long_t /* param */)
{
}

void TBTTab1_1::TabSelected()
{
}
void TBTTab1_1::TabUnSelected()
{
}

