// Author: Ryu Sawada <http://www.icepp.s.u-tokyo.ac.jp/%7Esawada>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TBTTab2_1                                                                  //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TBTTab2_1GeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TBWindow.h"
#include "generated/TBAnalyzer.h"
#include "tabs/TBTTab2_1.h"

// uncomment if you want to include headers of all folders
//#include "TBAllFolders.h"


ClassImp(TBTTab2_1)

void TBTTab2_1::Init()
{
}

void TBTTab2_1::EndInit()
{
}

void TBTTab2_1::EventHandler()
{
}

void TBTTab2_1::MenuClicked(TGPopupMenu * /* menu */,Long_t /* param */)
{
}

void TBTTab2_1::TabSelected()
{
}
void TBTTab2_1::TabUnSelected()
{
}

