////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// DOTHistos                                                                  //
//                                                                            //
// Description:                                                               //
//                                                                            //
//                                                                            //
// Usage:                                                                     //
//                                                                            //
//                                                                            //
// Status:                                                                    //
//                                                                            //
//                                                                            //
// To Do:                                                                     //
//                                                                            //
//                                                                            //
// Known Problems:                                                            //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/DOWindow.h"
#include "generated/DOAnalyzer.h"
#include "tabs/DOTHistos.h"

// uncomment if you want to include headers of all folders
//#include "DOAllFolders.h"


ClassImp(DOTHistos)

void DOTHistos::Init()
{
}

void DOTHistos::EndInit()
{
}

void DOTHistos::EventHandler()
{
}

void DOTHistos::MenuClicked(TGPopupMenu * /* menu */,Long_t /* param */)
{
}

void DOTHistos::TabSelected()
{
}
void DOTHistos::TabUnSelected()
{
}

