////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// HGUITGeneratedHisto                                                        //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/HGUITGeneratedHistoGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/HGUIWindow.h"
#include "generated/HGUIAnalyzer.h"
#include "tabs/HGUITGeneratedHisto.h"

// uncomment if you want to include headers of all folders
//#include "HGUIAllFolders.h"


ClassImp(HGUITGeneratedHisto)

void HGUITGeneratedHisto::Init()
{
}

void HGUITGeneratedHisto::EndInit()
{
}

void HGUITGeneratedHisto::EventHandler()
{
}

void HGUITGeneratedHisto::MenuClicked(TGPopupMenu * /* menu */,Long_t /* param */)
{
}

void HGUITGeneratedHisto::TabSelected()
{
}
void HGUITGeneratedHisto::TabUnSelected()
{
}

