// Author: Ryu Sawada

#ifndef HWTEnglish_H
#define HWTEnglish_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// HWTEnglish                                                                 //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/HWTEnglish_Base.h"
#include <TCanvas.h>
#include <TRootEmbeddedCanvas.h>
#include <TGLayout.h>
#include <TLatex.h>

class HWWindow;

class HWTEnglish : public HWTEnglish_Base
{
protected:
   TGVerticalFrame     *fVert;
   TRootEmbeddedCanvas *fCanvas;
   TLatex              *fText;

private:
   HWTEnglish(const HWTEnglish &c); // not implemented
   HWTEnglish &operator=(const HWTEnglish &c); // not implemented

public:
   HWTEnglish(HWWindow *window):HWTEnglish_Base(window)
   ,fVert(0)
   ,fCanvas(0)
   ,fText(0)
   {
   }

   virtual ~HWTEnglish()
   {
      delete fVert;
      delete fCanvas;
      delete fText;
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(HWTEnglish,1)
};

#endif   // HWTEnglish_H
