////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWR2TFillTree                                                              //
//                                                                            //
// Begin_Html                                                                 //
//                                                                            //
// Description:                                                               //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Usage:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Status:                                                                    //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// To Do:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Known Problems:                                                            //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// End_Html                                                                   //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//                                                                            //
//                                                                            //
// Followings are include files of folders. ROMEBuilder will update it with   //
// reading this source code when it is executed next time.                    //
#include "generated/TWR2Track.h"
#include "generated/TWR2RawPointerSplit.h"
#include "generated/TWR2RawPointerNoSplit.h"
#include "generated/TWR2RawSplit.h"
#include "generated/TWR2RawNoSplit.h"
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "RawData.h"
#include "generated/TWR2Analyzer.h"
#include "tasks/TWR2TFillTree.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "TWR2AllFolders.h"


ClassImp(TWR2TFillTree)

void TWR2TFillTree::Init()
{
}

void TWR2TFillTree::BeginOfRun()
{
   Int_t i;
   for (i=0; i < kNRawData; i++) {
      gAnalyzer->GetRawPointerSplitAt(i)->SetData(fRawData[i]);
      gAnalyzer->GetRawPointerNoSplitAt(i)->SetData(fRawData[i]);
   }
}

void TWR2TFillTree::Event()
{
   Int_t i;
   gAnalyzer->GetTrack()->Setntrack(kNRawData);
   gAnalyzer->GetTrack()->SetparticleidSize(kNRawData);

   ROMEString str;
   Int_t eve = gAnalyzer->GetCurrentEventNumber();

   for (i = 0; i < kNRawData; i++) {
      gAnalyzer->GetTrack()->SetparticleidAt(i,99);

      str.SetFormatted("%d %d %d", eve, i, 1);
      fRawData[i]->SetDataLength(str.Length() + 1);
      fRawData[i]->SetDataSize(str.Length() + 1);
      fRawData[i]->SetDataCopy(str.Data(), str.Length() + 1);

      str.SetFormatted("%d %d %d", eve, i, 2);
      gAnalyzer->GetRawSplitAt(i)->GetData()->SetDataLength(str.Length() + 1);
      gAnalyzer->GetRawSplitAt(i)->GetData()->SetDataSize(str.Length() + 1);
      gAnalyzer->GetRawSplitAt(i)->GetData()->SetDataCopy(str.Data(), str.Length() + 1);

      gAnalyzer->GetRawNoSplitAt(i)->GetData()->SetDataLength(str.Length() + 1);
      gAnalyzer->GetRawNoSplitAt(i)->GetData()->SetDataSize(str.Length() + 1);
      gAnalyzer->GetRawNoSplitAt(i)->GetData()->SetDataCopy(str.Data(), str.Length() + 1);
   }
}

void TWR2TFillTree::EndOfRun()
{
}

void TWR2TFillTree::Terminate()
{
}

