////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TCUTGTFillHisto                                                            //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
//                                                                            //
// This task contains the following histgrams :                               //
//    MyHisto                                                                 //
// This task contains the following graphs :                                  //
//    MyCutG                                                                  //
//                                                                            //
// The histograms/graph are created and saved automaticaly by the task.       //
//                                                                            //
// The following method can be used to get a handle of the histogram/graph :  //
//                                                                            //
// Get<Histogram/Graph Name>()                                                //
//                                                                            //
// For histogram/graph arrays use :                                           //
//                                                                            //
// Get<Histogram/Graph Name>At(Int_t index)                                   //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TCUTGTFillHistoGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
#include "generated/TCUTGAnalyzer.h"

#include "include/tasks/TCUTGTFillHisto.h"
#include <TRandom.h>
#include "Riostream.h"

// uncomment if you want to include headers of all folders
//#include "TCUTGAllFolders.h"


ClassImp(TCUTGTFillHisto)

void TCUTGTFillHisto::Init()
{
}

void TCUTGTFillHisto::BeginOfRun()
{
}

void TCUTGTFillHisto::Event()
{
   GetMyHisto()->Fill(gRandom->Gaus(0,10));
   GetMyCutG()->SetPoint(0,-10.5,0);
   GetMyCutG()->SetPoint(1,-10.5,+100);
   GetMyCutG()->SetPoint(2,+10.5,+100);
   GetMyCutG()->SetPoint(3,+10.5,0);
   GetMyCutG()->SetPoint(4,-10.5,0);
   GetMyCutG()->SetLineColor(2);
}

void TCUTGTFillHisto::EndOfRun()
{
}

void TCUTGTFillHisto::Terminate()
{
}

