//// Author: 
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// XYZTADCCalib                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
// This file has been generated by the ROMEBuilder.                           //
//                                                                            //
// This task contains the following histgrams :
// ADCHisto
//
// The histograms are created and saved automaticaly by the task.
//
// The following methods can be used to fill the histogram and to set the
// right name,title and binwidth of the histogram :
//
// Fill<Histogram Name>(double value,double weight)
//
// For histogram arrays use :
//
// Fill<Histogram Name>At(int index,double value,double weight)
//
// If more histogram functions are needed use the following function the get
// a handle to the histogram and use the root functions.
//
// Get<Histogram Name>Handle()
//
// For histogram arrays use :
//
// Get<Histogram Name>HandleAt(int index)
//                                                                            //
/////////////////////////////////////----///////////////////////////////////////

#include <include/tasks/XYZTADCCalib.h>
#include <Riostream.h>

ClassImp(XYZTADCCalib)

void XYZTADCCalib::Init()
{
}

void XYZTADCCalib::BeginOfRun()
{
}

void XYZTADCCalib::Event()
{
    for (int i=0;i<257;i++) {
       float pmtData = gAnalyzer->GetPMTDataAt(i)->GetADC();
       float pedestal = gAnalyzer->GetCalibAt(i)->GetADCPedestal();
       FillADCHistoAt(i,pmtData - pedestal);
    }
} 
void XYZTADCCalib::EndOfRun()
{
    for (int i=0;i<257;i++) {
       DrawADCHistoAt(i);
    }
}

void XYZTADCCalib::Terminate()
{
}

