//// Author: 
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// XYZTReadMidas                                                              //
//                                                                            //
//                                                                            //
//                                                                            //
// This file has been generated by the ROMEBuilder.                           //
//                                                                            //
// This task contains the following histgrams :
//
// The histograms are created and saved automaticaly by the task.
//
// The following methods can be used to fill the histogram and to set the
// right name,title and binwidth of the histogram :
//
// Fill<Histogram Name>(double value,double weight)
//
// For histogram arrays use :
//
// Fill<Histogram Name>At(int index,double value,double weight)
//
// If more histogram functions are needed use the following function the get
// a handle to the histogram and use the root functions.
//
// Get<Histogram Name>Handle()
//
// For histogram arrays use :
//
// Get<Histogram Name>HandleAt(int index)
//                                                                            //
/////////////////////////////////////----///////////////////////////////////////

#include "XYZTReadMidas.h"
#include <Riostream.h>

ClassImp(XYZTReadMidas)

void XYZTReadMidas::Init()
{
}

void XYZTReadMidas::BeginOfRun()
{
}
#define gNumberOfPMT 257
void XYZTReadMidas::Event()
{
   for (int i=0;i<gNumberOfPMT;i++) {
//      int iadc = fAnalyzer->GetCMPMTInfoAt(i)->GetADCID();
	   Float_t adcValue = fAnalyzer->GetADC0BankAt(i);
      fAnalyzer->GetCMPMTDataAt(i)->SetADC(adcValue);
   }
}

void XYZTReadMidas::EndOfRun()
{
}

void XYZTReadMidas::Terminate()
{
}

