////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWR3TCheckValues                                                           //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     MyFolder                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TWR3TCheckValuesGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TWR3Analyzer.h"
#include "tasks/TWR3TCheckValues.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "TWR3AllFolders.h"


ClassImp(TWR3TCheckValues)

void TWR3TCheckValues::Init()
{
}

void TWR3TCheckValues::BeginOfRun()
{
}

void TWR3TCheckValues::Event()
{
   Int_t i, j;

   if (gAnalyzer->GetMyFolder()->GetTSFSF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSFSF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSFSF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSFST()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSFST()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSFST()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSFSF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSFSF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSFSF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSFST()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSFST()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSFST()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSTSF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSTSF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSTSF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSTST()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSTST()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSTST()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSTSF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSTSF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSTSF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSTST()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSTST()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSTST()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }

   if (gAnalyzer->GetMyFolder()->GetTSFFF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSFFF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSFFF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSFFT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSFFT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSFFT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSFFF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSFFF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSFFF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSFFT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSFFT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSFFT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSTFF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSTFF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSTFF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSTFT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSTFT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSTFT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSTFF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSTFF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSTFF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSTFT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSTFT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSTFT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }

   if (gAnalyzer->GetMyFolder()->GetTSFVF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSFVF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSFVF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSFVT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSFVT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSFVT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSFVF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSFVF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSFVF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSFVT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSFVT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSFVT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSTVF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSTVF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSTVF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetTSTVT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetTSTVT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetTSTVT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSTVF()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSTVF()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSTVF()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }
   if (gAnalyzer->GetMyFolder()->GetFSTVT()->GetNumber() != 5) { cerr<<"error"<<endl; }
   for (j = 0; j < 5; j++) {
      if (gAnalyzer->GetMyFolder()->GetFSTVT()->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
      if (gAnalyzer->GetMyFolder()->GetFSTVT()->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
   }

   for (i = 0; i < 10; i++) {
      if (gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }

      if (gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }

      if (gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
   }

   if (gAnalyzer->GetMyFolder()->GetTVFSFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVFSTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVFSFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVFSTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVTSFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVTSTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVTSFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVTSTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVFFFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVFFTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVFFFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVFFTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVTFFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVTFTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVTFFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVTFTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVFVFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVFVTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVFVFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVFVTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVTVFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetTVTVTSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVTVFSize() != 10) { cerr<<"error"<<endl; }
   if (gAnalyzer->GetMyFolder()->GetFVTVTSize() != 10) { cerr<<"error"<<endl; }

   for (i = 0; i < 10; i++) {
      if (gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }

      if (gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }

      if (gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
      if (gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->GetNumber() != 5) { cerr<<"error"<<endl; }
      for (j = 0; j < 5; j++) {
         if (gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->GetFixedArrayAt(j) != 5) { cerr<<"error"<<endl; }
         if (gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->GetVariableArrayAt(j) != 5) { cerr<<"error"<<endl; }
      }
   }
}

void TWR3TCheckValues::EndOfRun()
{
}

void TWR3TCheckValues::Terminate()
{
}
