////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWR3TPrintValues                                                           //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     MyFolder                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TWR3TPrintValuesGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TWR3Analyzer.h"
#include "tasks/TWR3TPrintValues.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "TWR3AllFolders.h"


ClassImp(TWR3TPrintValues)

//______________________________________________________________________________
void TWR3TPrintValues::Init()
{
}

//______________________________________________________________________________
void TWR3TPrintValues::BeginOfRun()
{
}

//______________________________________________________________________________
void TWR3TPrintValues::Event()
{
   gAnalyzer->GetMyFolder()->Print("");
}

//______________________________________________________________________________
void TWR3TPrintValues::EndOfRun()
{
}

//______________________________________________________________________________
void TWR3TPrintValues::Terminate()
{
}

