// Author: Ryu Sawada

#ifndef SBTTab2_H
#define SBTTab2_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// SBTTab2                                                                    //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/SBTTab2_Base.h"

class SBTTab2 : public SBTTab2_Base
{
protected:

public:
   SBTTab2():SBTTab2_Base()
   {
   }

   virtual ~SBTTab2()
   {
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(SBTTab2,1)
};

#endif   // SBTTab2_H
