// Author: Ryu Sawada

#ifndef TMTT2_H
#define TMTT2_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TMTT2                                                                      //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/TMTT2_Base.h"
#include <TCanvas.h>
#include <TRootEmbeddedCanvas.h>
#include <TGLayout.h>
#include <TLatex.h>

class TMTT2 : public TMTT2_Base
{
protected:
   TGVerticalFrame     *fVert;
   TRootEmbeddedCanvas *fCanvas;
   TLatex              *fText;

public:
   TMTT2():TMTT2_Base()
   {
      fVert   = 0;
      fCanvas = 0;
      fText   = 0;
   }

   virtual ~TMTT2()
   {
      delete fVert;
      delete fCanvas;
      delete fText;
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(TMTT2,1)
};

#endif   // TMTT2_H
