// Author: Ryu Sawada

#ifndef TMTT1_H
#define TMTT1_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TMTT1                                                                      //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/TMTT1_Base.h"
#include <TCanvas.h>
#include <TRootEmbeddedCanvas.h>
#include <TGLayout.h>
#include <TLatex.h>

class TMWindow;

class TMTT1 : public TMTT1_Base
{
protected:
   TGVerticalFrame     *fVert;
   TRootEmbeddedCanvas *fCanvas;
   TLatex              *fText;

private:
   TMTT1(const TMTT1 &c); // not implemented
   TMTT1 &operator=(const TMTT1 &c); // not implemented

public:
   TMTT1(TMWindow *window):TMTT1_Base(window)
   ,fVert(0)
   ,fCanvas(0)
   ,fText(0)
   {
   }

   virtual ~TMTT1()
   {
      delete fVert;
      delete fCanvas;
      delete fText;
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(TMTT1,1)
};

#endif   // TMTT1_H
