////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TCUTGTHistos                                                               //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TCUTGTHistosGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TCUTGWindow.h"
#include "generated/TCUTGAnalyzer.h"
#include "tabs/TCUTGTHistos.h"

// uncomment if you want to include headers of all folders
//#include "TCUTGAllFolders.h"


ClassImp(TCUTGTHistos)

void TCUTGTHistos::Init()
{
}

void TCUTGTHistos::EndInit()
{
}

void TCUTGTHistos::EventHandler()
{
}

void TCUTGTHistos::MenuClicked(TGPopupMenu * /* menu */, Long_t /* param */)
{
}

void TCUTGTHistos::TabSelected()
{
}

void TCUTGTHistos::TabUnSelected()
{
}

void TCUTGTHistos::SetupPads(Int_t nx, Int_t ny, Bool_t redraw)
{
   BaseSetupPads(nx, ny, redraw);
}

void TCUTGTHistos::Display(bool processEvents)
{
   BaseDisplay(processEvents);
}

