////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// This file has been generated by the ROMEBuilder.                           //
// Manual changes to this file will always be overwritten by the builder.     //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef HGTMakeHistogram_H
#define HGTMakeHistogram_H

#include<TH1.h>
#include<TH2.h>
#include<TH3.h>
#include<ROMETask.h>
#include <include/framework/HGAnalyzer.h>

class HGTMakeHistogram : public ROMETask
{
protected:
   TH1F*      fhAdc;  // ADC
   bool       fhAdcAccumulation; // Accumulation Flag for the hAdc
public:
   // Constructor
   HGTMakeHistogram(const char *name,const char *title):ROMETask(name,title)
   { fEventID = '1'; fVersion = 1; fHasHistograms = true; fhAdcAccumulation = true; };
   // User Methods
   void FillhAdc(double x,double weight=1) { fhAdc->Fill(x,weight); };
   void DrawhAdc() { fhAdc->Draw(); };
   TH1F* GethAdc() { return fhAdc; };
   Bool_t ishAdcAccumulation() { return fhAdcAccumulation; };
   void SethAdcAccumulation(Bool_t flag) { fhAdcAccumulation = flag; };
protected:
   // Event Methods
   virtual void Init();
   virtual void BeginOfRun();
   virtual void Event();
   virtual void EndOfRun();
   virtual void Terminate();

   // Histo Methods
   virtual void BookHisto();
   virtual void ResetHisto();


   ClassDef(HGTMakeHistogram,1)
};

inline void HGTMakeHistogram::BookHisto() {
   TFolder *ADCFolder = GetHistoFolder()->AddFolder("ADC","ADC");
   fhAdc = new TH1F("hAdc","ADC",3996,10,3996);
   ADCFolder->Add(fhAdc);
   fhAdc->GetXaxis()->SetTitle("");
   fhAdc->GetYaxis()->SetTitle("");
   fhAdc->GetZaxis()->SetTitle("");
}

inline void HGTMakeHistogram::ResetHisto() {
   if (!ishAdcAccumulation()) fhAdc->Reset();
}

#endif   // HGTMakeHistogram_H
