////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// DOTFillHisto                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
//                                                                            //
//  This task contains the following histgrams :                              //
//     MyHisto                                                                //
//     MyOtherHisto                                                           //
//                                                                            //
// The histograms are created and saved automaticaly by the task.             //
//                                                                            //
// The following method can be used to fill a histogram :                     //
//                                                                            //
// Fill<Histogram Name>(Double_t value,Double_t weight)                       //
//                                                                            //
// For histogram arrays use :                                                 //
//                                                                            //
// Fill<Histogram Name>At(Int_t index,Double_t value,Double_t weight)         //
//                                                                            //
// If more histogram functions are needed use the following function the get  //
//  a handle to the histogram and use the root functions.                     //
//                                                                            //
// Get<Histogram Name>()                                                      //
//                                                                            //
// For histogram arrays use :                                                 //
//                                                                            //
// Get<Histogram Name>At(Int_t index)                                         //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
#include "generated/DOAnalyzer.h"

#include "include/tasks/DOTFillHisto.h"
#include <TRandom.h>
#include "Riostream.h"

ClassImp(DOTFillHisto)

void DOTFillHisto::Init()
{
}

void DOTFillHisto::BeginOfRun()
{
}

void DOTFillHisto::Event()
{
   GetMyHistoAt(0)->Fill(gRandom->Gaus(0,10));
   GetMyHistoAt(1)->Fill(gRandom->Gaus(0,20));
   GetMyHistoAt(2)->Fill(gRandom->Gaus(0,30));
   GetMyOtherHistoAt(0)->Fill(gRandom->Gaus(10,10));
   GetMyOtherHistoAt(1)->Fill(gRandom->Gaus(10,20));
   GetMyOtherHistoAt(2)->Fill(gRandom->Gaus(10,30));
}

void DOTFillHisto::EndOfRun()
{
}

void DOTFillHisto::Terminate()
{
}

