#ifndef NFTHistos_H
#define NFTHistos_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// NFTHistos                                                                  //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include <TH1.h>
#include <TRootEmbeddedCanvas.h>
#include "generated/NFTHistos_Base.h"

class NFWindow;


class NFTHistos : public NFTHistos_Base
{
protected:
   TH1F *histo2;
   TRootEmbeddedCanvas *fCanvas;

private:
   NFTHistos(const NFTHistos &c); // not implemented
   NFTHistos &operator=(const NFTHistos &c); // not implemented

public:
   NFTHistos(NFWindow* window):NFTHistos_Base(window)
   ,histo2(0)
   ,fCanvas(0)
   {
   }

   virtual ~NFTHistos()
   {
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(NFTHistos,1)
};

#endif   // NFTHistos_H
