////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWRTFillTree                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//                                                                            //
//                                                                            //
// Followings are include files of folders. ROMEBuilder will update it with   //
// reading this source code when it is executed next time.                    //
#include "generated/TWRData1.h"
#include "generated/TWRData2.h"
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
#include "generated/TWRAnalyzer.h"

#include "include/tasks/TWRTFillTree.h"
#include "Riostream.h"

ClassImp(TWRTFillTree)

void TWRTFillTree::Init()
{
}

void TWRTFillTree::BeginOfRun()
{
}

void TWRTFillTree::Event()
{
   gAnalyzer->GetData1()->SetValue1((int)gAnalyzer->GetCurrentEventNumber());
   if (gAnalyzer->GetCurrentEventNumber() % 2)
      gAnalyzer->GetData2()->SetValue2((int)gAnalyzer->GetCurrentEventNumber());
}

void TWRTFillTree::EndOfRun()
{
}

void TWRTFillTree::Terminate()
{
}

