////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWRTFillTree                                                               //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     Data1                                                                  //
//     Data2                                                                  //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TWRTFillTreeGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
#include "generated/TWRAnalyzer.h"

#include "include/tasks/TWRTFillTree.h"
#include "Riostream.h"

ClassImp(TWRTFillTree)

void TWRTFillTree::Init()
{
}

void TWRTFillTree::BeginOfRun()
{
}

void TWRTFillTree::Event()
{
   gAnalyzer->GetData1()->SetValue1((int)gAnalyzer->GetCurrentEventNumber());
   if (gAnalyzer->GetCurrentEventNumber() % 2)
      gAnalyzer->GetData2()->SetValue2((int)gAnalyzer->GetCurrentEventNumber());
}

void TWRTFillTree::EndOfRun()
{
}

void TWRTFillTree::Terminate()
{
}

