////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWRTFillTree                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     Data                                                                   //
//                                                                            //
//                                                                            //
// Followings are include files of folders. ROMEBuilder will update it with   //
// reading this source code when you execute it next time.                    //
#include "include/generated/TWRData.h"
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "include/generated/TWRTFillTree.h"
#include "Riostream.h"

ClassImp(TWRTFillTree)

void TWRTFillTree::Init()
{
}

void TWRTFillTree::BeginOfRun()
{
}

void TWRTFillTree::Event()
{
   gAnalyzer->GetData()->SetValue((int)gAnalyzer->GetCurrentEventNumber());
}

void TWRTFillTree::EndOfRun()
{
}

void TWRTFillTree::Terminate()
{
}

