////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// NFTFillHistoAndFolder                                                      //
//                                                                            //
// Begin_Html                                                                 //
//                                                                            //
// Description:                                                               //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Usage:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Status:                                                                    //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// To Do:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Known Problems:                                                            //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// End_Html                                                                   //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//                                                                            //
// This task contains the following histgrams :                               //
//    Histo1                                                                  //
//                                                                            //
// The histograms/graph are created and saved automaticaly by the task.       //
//                                                                            //
// The following method can be used to get a handle of the histogram/graph :  //
//                                                                            //
// Get<Histogram/Graph Name>()                                                //
//                                                                            //
// For histogram/graph arrays use :                                           //
//                                                                            //
// Get<Histogram/Graph Name>At(Int_t index)                                   //
//                                                                            //
// Followings are include files of folders. ROMEBuilder will update it with   //
// reading this source code when it is executed next time.                    //
#include "generated/NFGaussData.h"
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////
#include "generated/NFAnalyzer.h"

#include <TRandom.h>
#include <TSystem.h>
#include "include/tasks/NFTFillHistoAndFolder.h"
#include "Riostream.h"

ClassImp(NFTFillHistoAndFolder)

void NFTFillHistoAndFolder::Init()
{
}

void NFTFillHistoAndFolder::BeginOfRun()
{
   gAnalyzer->GetGaussData()->SetBinSize(200);
}

void NFTFillHistoAndFolder::Event()
{
   double value = gRandom->Gaus(0,20);
   FillHisto1(value);
   int ivalue = (int)(value+100);
   gSystem->Sleep(10);
   if (ivalue>=0 && ivalue<200)
      gAnalyzer->GetGaussData()->SetBinAt(ivalue,gAnalyzer->GetGaussData()->GetBinAt(ivalue)+1);
}

void NFTFillHistoAndFolder::EndOfRun()
{
}

void NFTFillHistoAndFolder::Terminate()
{
}

