# User editable Makefile for the fomonitor
#
# Description:
# 1) Add compile(link) options to Flags(Libraries), e.g. Flags += -g -O2 -Wall
# 2) Add mySource.obj to the list of objects, e.g. objects += mySource.obj
# 3) Add compile statment, e.g.
#       obj/mySource.obj: mySource.cpp
#          g++ -c $(Flags) $(Includes) mySource.cpp -o obj/mySource.obj
#
DictionaryHeaders += romeproject/include/generated/FORunInfo.h romeproject/include/generated/FOPMTData.h
