////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TWR3TFillTree                                                              //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     MyFolder                                                               //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/TWR3TFillTreeGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TWR3Analyzer.h"
#include "tasks/TWR3TFillTree.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "TWR3AllFolders.h"


ClassImp(TWR3TFillTree)

void TWR3TFillTree::Init()
{
}

void TWR3TFillTree::BeginOfRun()
{
}

void TWR3TFillTree::Event()
{
   Int_t i, j;

   gAnalyzer->GetMyFolder()->GetTSFSF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSFSF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSFSF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSFSF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetTSFST())
      gAnalyzer->GetMyFolder()->SetTSFST(new TWR3MySupportFolderA());
   gAnalyzer->GetMyFolder()->GetTSFST()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSFST()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSFST()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSFST()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetFSFSF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSFSF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSFSF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSFSF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetFSFST())
      gAnalyzer->GetMyFolder()->SetFSFST(new TWR3MySupportFolderA());
   gAnalyzer->GetMyFolder()->GetFSFST()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSFST()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSFST()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSFST()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetTSTSF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSTSF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSTSF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSTSF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetTSTST())
      gAnalyzer->GetMyFolder()->SetTSTST(new TWR3MySupportFolderA());
   gAnalyzer->GetMyFolder()->GetTSTST()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSTST()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSTST()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSTST()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetFSTSF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSTSF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSTSF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSTSF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetFSTST())
      gAnalyzer->GetMyFolder()->SetFSTST(new TWR3MySupportFolderA());
   gAnalyzer->GetMyFolder()->GetFSTST()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSTST()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSTST()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSTST()->SetVariableArrayAt(j, 5);
   }

   gAnalyzer->GetMyFolder()->GetTSFFF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSFFF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSFFF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSFFF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetTSFFT())
      gAnalyzer->GetMyFolder()->SetTSFFT(new TWR3MySupportFolderB());
   gAnalyzer->GetMyFolder()->GetTSFFT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSFFT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSFFT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSFFT()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetFSFFF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSFFF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSFFF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSFFF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetFSFFT())
      gAnalyzer->GetMyFolder()->SetFSFFT(new TWR3MySupportFolderB());
   gAnalyzer->GetMyFolder()->GetFSFFT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSFFT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSFFT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSFFT()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetTSTFF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSTFF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSTFF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSTFF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetTSTFT())
      gAnalyzer->GetMyFolder()->SetTSTFT(new TWR3MySupportFolderB());
   gAnalyzer->GetMyFolder()->GetTSTFT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSTFT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSTFT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSTFT()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetFSTFF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSTFF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSTFF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSTFF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetFSTFT())
      gAnalyzer->GetMyFolder()->SetFSTFT(new TWR3MySupportFolderB());
   gAnalyzer->GetMyFolder()->GetFSTFT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSTFT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSTFT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSTFT()->SetVariableArrayAt(j, 5);
   }

   gAnalyzer->GetMyFolder()->GetTSFVF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSFVF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSFVF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSFVF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetTSFVT())
      gAnalyzer->GetMyFolder()->SetTSFVT(new TWR3MySupportFolderC());
   gAnalyzer->GetMyFolder()->GetTSFVT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSFVT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSFVT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSFVT()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetFSFVF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSFVF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSFVF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSFVF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetFSFVT())
      gAnalyzer->GetMyFolder()->SetFSFVT(new TWR3MySupportFolderC());
   gAnalyzer->GetMyFolder()->GetFSFVT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSFVT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSFVT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSFVT()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetTSTVF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSTVF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSTVF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSTVF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetTSTVT())
      gAnalyzer->GetMyFolder()->SetTSTVT(new TWR3MySupportFolderC());
   gAnalyzer->GetMyFolder()->GetTSTVT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetTSTVT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetTSTVT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetTSTVT()->SetVariableArrayAt(j, 5);
   }
   gAnalyzer->GetMyFolder()->GetFSTVF()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSTVF()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSTVF()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSTVF()->SetVariableArrayAt(j, 5);
   }
   if (!gAnalyzer->GetMyFolder()->GetFSTVT())
      gAnalyzer->GetMyFolder()->SetFSTVT(new TWR3MySupportFolderC());
   gAnalyzer->GetMyFolder()->GetFSTVT()->SetNumber(5);
   gAnalyzer->GetMyFolder()->GetFSTVT()->SetVariableArraySize(5);
   for (j = 0; j < 5; j++) {
      gAnalyzer->GetMyFolder()->GetFSTVT()->SetFixedArrayAt(j, 5);
      gAnalyzer->GetMyFolder()->GetFSTVT()->SetVariableArrayAt(j, 5);
   }

   for (i = 0; i < 10; i++) {
      gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFFSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFFSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFFSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFFSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFTSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFTSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFTSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFTSTAt(i)->SetVariableArrayAt(j, 5);
      }

      gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFFFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFFFTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFFFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFFFTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFTFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFTFTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFTFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFTFTAt(i)->SetVariableArrayAt(j, 5);
      }

      gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFFVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFFVTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFFVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFFVTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFTVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTFTVTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFTVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFFTVTAt(i)->SetVariableArrayAt(j, 5);
      }
   }


   gAnalyzer->GetMyFolder()->SetTVFSFSize(10);
   gAnalyzer->GetMyFolder()->SetTVFSTSize(10);
   gAnalyzer->GetMyFolder()->SetFVFSFSize(10);
   gAnalyzer->GetMyFolder()->SetFVFSTSize(10);
   gAnalyzer->GetMyFolder()->SetTVTSFSize(10);
   gAnalyzer->GetMyFolder()->SetTVTSTSize(10);
   gAnalyzer->GetMyFolder()->SetFVTSFSize(10);
   gAnalyzer->GetMyFolder()->SetFVTSTSize(10);
   gAnalyzer->GetMyFolder()->SetTVFFFSize(10);
   gAnalyzer->GetMyFolder()->SetTVFFTSize(10);
   gAnalyzer->GetMyFolder()->SetFVFFFSize(10);
   gAnalyzer->GetMyFolder()->SetFVFFTSize(10);
   gAnalyzer->GetMyFolder()->SetTVTFFSize(10);
   gAnalyzer->GetMyFolder()->SetTVTFTSize(10);
   gAnalyzer->GetMyFolder()->SetFVTFFSize(10);
   gAnalyzer->GetMyFolder()->SetFVTFTSize(10);
   gAnalyzer->GetMyFolder()->SetTVFVFSize(10);
   gAnalyzer->GetMyFolder()->SetTVFVTSize(10);
   gAnalyzer->GetMyFolder()->SetFVFVFSize(10);
   gAnalyzer->GetMyFolder()->SetFVFVTSize(10);
   gAnalyzer->GetMyFolder()->SetTVTVFSize(10);
   gAnalyzer->GetMyFolder()->SetTVTVTSize(10);
   gAnalyzer->GetMyFolder()->SetFVTVFSize(10);
   gAnalyzer->GetMyFolder()->SetFVTVTSize(10);

   for (i = 0; i < 10; i++) {
      gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVFSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVFSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVFSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVFSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVTSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVTSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVTSFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVTSTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->SetNumber(5);

      gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVFFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVFFTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVFFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVFFTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVTFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVTFTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVTFFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVTFTAt(i)->SetVariableArrayAt(j, 5);
      }

      gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVFVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVFVTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVFVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVFVTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVTVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetTVTVTAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVTVFAt(i)->SetVariableArrayAt(j, 5);
      }
      gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->SetNumber(5);
      gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->SetVariableArraySize(5);
      for (j = 0; j < 5; j++) {
         gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->SetFixedArrayAt(j, 5);
         gAnalyzer->GetMyFolder()->GetFVTVTAt(i)->SetVariableArrayAt(j, 5);
      }
   }
}

void TWR3TFillTree::EndOfRun()
{
}

void TWR3TFillTree::Terminate()
{
}
