#ifndef ROMEVersion
#define ROMEVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROME_VERSION_CODE >= ROME_VERSION(2,5)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROME_RELEASE "2.5"
#define ROME_REVISION "$Rev$"
#define ROME_REVISION_CODE 1
#define ROME_STABLE 0
#define ROME_RELEASE_DATE "Aug  6 2006"
#define ROME_RELEASE_TIME "20:04:28"
#define ROME_VERSION_CODE 517
#define ROME_VERSION(a,b) (((a) << 8) + (b))

#endif
