////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// BFTFillFolder                                                              //
//                                                                            //
// Begin_Html                                                                 //
//                                                                            //
// Description:                                                               //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Usage:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Status:                                                                    //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// To Do:                                                                     //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// Known Problems:                                                            //
// <p>                                                                        //
//                                                                            //
//                                                                            //
// <p>                                                                        //
// End_Html                                                                   //
//                                                                            //
// The event methods have been written by .                                   //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//                                                                            //
//                                                                            //
// Generated header file containing necessary includes                        //
#include "generated/BFTFillFolderGeneratedIncludes.h"
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/BFAnalyzer.h"
#include "tasks/BFTFillFolder.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "BFAllFolders.h"


ClassImp(BFTFillFolder)

void BFTFillFolder::Init()
{
}

void BFTFillFolder::BeginOfRun()
{
}

void BFTFillFolder::Event()
{
   gAnalyzer->GetMyFolder()->SetMyValue((int)gAnalyzer->GetCurrentEventNumber());
   gAnalyzer->GetMyFolder()->SetMyBaseValue((int)gAnalyzer->GetCurrentEventNumber()*10);
}

void BFTFillFolder::EndOfRun()
{
}

void BFTFillFolder::Terminate()
{
}

